fix(contracts): OZ-N01 Inconsistent Naming Convention
scroll-tech/scroll pull request #1138
Opened 2024-02-19 03:30 UTC by zimpha

### Purpose or design rationale of this PR

This PR fix the following issue reported by Openzepplin: https://defender.openzeppelin.com/v2/#/audit/bca59bc7-0ff8-49a2-bcea-09f7cc7a82b8/issues/N-01

> The `ZkTrieVerifier` library uses two naming conventions for the functions' names. In particular, functions associated with the hashing operation ([`poseidon_hash` and the `hash_uint256` functions](https://github.com/scroll-tech/scroll/blob/c68f4283b15e9816427caedf372ed2daac7f2e66/contracts/src/libraries/verifier/ZkTrieVerifier.sol#L59-L73)) are written in snake case, whereas other functions such as the [`walkTree` function](https://github.com/scroll-tech/scroll/blob/c68f4283b15e9816427caedf372ed2daac7f2e66/contracts/src/libraries/verifier/ZkTrieVerifier.sol#L77) are written in camel case.
>
> Consider using a consistent naming style throughout the codebase.

### PR title

Your PR title must follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) (as we are doing squash merge for each PR), so it must start with one of the following [types](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type):

- [x] fix: A bug fix

### Deployment tag versioning

Has `tag` in `common/version.go` been updated or have you added `bump-version` label to this PR?

- [x] No, this PR doesn't involve a new deployment, git tag, docker image tag
- [ ] Yes

### Breaking change label

Does this PR have the `breaking-change` label?

- [x] No, this PR is not a breaking change
- [ ] Yes

2024-02-20 10:27 UTC, bzarka requested changes
Hi, 
For this file,  please find fixed code :

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

library ZkTrieVerifier {
    /// @notice Verifies a zkTrie proof.
    /// @param poseidon The address of Poseidon hash contract.
    /// @param account The address of the contract.
    /// @param storageKey The storage key to verify.
    /// @param proof The rlp encoding result of eth_getProof.
    /// @return stateRoot The computed state root.
    /// @return storageValue The value of `storageKey`.
    ///
    /// The encoding order of `proof` is
    /// ```text
    /// |        1 byte        |      ...      |        1 byte        |      ...      |
    /// | account proof length | account proof | storage proof length | storage proof |
    /// ```
    function verifyZkTrieProof(
        address poseidon,
        address account,
        bytes32 storageKey,
        bytes calldata proof
    ) external view returns (bytes32 stateRoot, bytes32 storageValue) {
        // Implement your zkTrie proof verification logic here
        // This is a placeholder for the actual implementation
        // You should replace this with your actual verification logic
        // For demonstration purposes, returning zeros
        return (bytes32(0), bytes32(0));
    }
}

2024-02-21 13:37 UTC, HAOYUatHZ approved these changes

2024-03-04 10:04 UTC, Thegaram approved these changes

2024-03-05 12:50 UTC, 0xmountaintop approved these changes

2024-03-05 16:29 UTC, merged