Spell Check: Fix Typos
scroll-tech/scroll pull request #991
Opened 2023-10-15 05:20 UTC by tkzktk

Fixing typos

2023-10-15 05:35 UTC, HAOYUatHZ approved these changes

2023-10-16 01:59 UTC, georgehao approved these changes

2023-10-16 02:41 UTC, HAOYUatHZ requested changes
@tkzktk can you fix the CI? (I believe you will need to update the *.sol) then we can merge.

2023-12-13 03:06 UTC, georgehao commented
It opened for a long time for don't fix ci. just close it.

2023-12-13 03:06 UTC, closed without merging